default:
  interruptible: true
  artifacts:
    expose_as: testlog
    expire_in: 30 days
    paths:
      - build-arch-gcc/meson.logs/testlog.json
      - build-arch-gcc/meson.logs/testlog.junit.xml
      - build-arch-gcc/meson.logs/testlog.txt

arch-gcc:
  tags:
    - docker
  image:
    name: robinmarchart/meson-builder:arch-gcc
  script:
    - "meson build-arch-gcc -Dbuild_test=true"
    - "cd build-arch-gcc;meson test"
