default:
  interruptible: true
  artifacts:
    expose_as: testlog
    expire_in: 30 days
    paths:
      - build/meson-logs/testlog.junit.xml
      - build/meson-logs/testlog.txt
arch-gcc:
  tags:
    - docker
  image:
    name: robinmarchart/meson-builder:arch-gcc
  script:
    - "meson build -Dbuild_test=true"
    - "cd build;meson test"
arch-clang:
  tags:
    - docker
  image:
    name: robinmarchart/meson-builder:arch-clang
  script:
    - "meson build -Dbuild_test=true"
    - "cd build;meson test"
debian-gcc:
  tags:
    - docker
  image:
    name: robinmarchart/meson-builder:arch-gcc
  script:
    - "meson build -Dbuild_test=true"
    - "cd build;meson test"
debian-gcc:
  tags:
    - docker
  image:
    name: robinmarchart/meson-builder:arch-gcc
  script:
    - "meson build -Dbuild_test=true"
    - "cd build;meson test"
