default:
  interruptible: true
arch-gcc:
  tags:
    - docker
  image:
    name: robinmarchart/meson-builder:arch-gcc
  script:
    - "meson build -Dbuild_test=true"
    - "cd build;meson test"
arch-clang:
  tags:
    - docker
  image:
    name: robinmarchart/meson-builder:arch-clang
  script:
    - "meson build -Dbuild_test=true"
    - "cd build;meson test"
debian-gcc:
  tags:
    - docker
  image:
    name: robinmarchart/meson-builder:arch-gcc
  script:
    - "meson build -Dbuild_test=true"
    - "cd build;meson test"
debian-clang:
  tags:
    - docker
  image:
    name: robinmarchart/meson-builder:arch-clang
  script:
    - "meson build -Dbuild_test=true"
    - "cd build;meson test"
